### ISSUE TITLE
Mix between subjects?

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#32] opened 2021-08-02 00:57 UTC
These two plots for the brain and spinal cord show a different number of sessions. I suspect a mixup between subject numbering (eg: subject 4 in spinal cord corresponding to subject 5 in the brain):

![Screen Shot 2021-08-01 at 8 56 18 PM](https://user-images.githubusercontent.com/2482071/127791265-38e1f4b7-c1f0-4082-a74c-a77cb37a0e78.png)

![Screen Shot 2021-08-01 at 8 56 01 PM](https://user-images.githubusercontent.com/2482071/127791267-60afa8ce-11f1-4526-b409-51617b0d215c.png)

**Comment by zelenkastiot** [comment] 2021-08-02 01:31
If understood correctly the issue is the correct subjects displayed in the plots.  But, according to this output, which extracts the values/sessions/subjects, what it displays in coresponds to the csv data.

- Output/plotting in code:  

![image](https://user-images.githubusercontent.com/37374247/127792482-1408f791-5edc-459e-b67d-b94a7b54ce9d.png)

- Rows in spinal data [`csa-GM_T2s.csv`]: 

![image](https://user-images.githubusercontent.com/37374247/127792767-ba197042-de68-4421-8e9c-840eb9c9922a.png)



- Rows in brain data [`results-neuromod-anat-brain-qmri.csv`]:

![image](https://user-images.githubusercontent.com/37374247/127792682-b1504ae9-3ef2-46f3-a886-f553fd376572.png)

**Comment by jcohenadad** [comment] 2021-08-02 01:35
OK, it should be fine then. So we need to understand why the number of sessions differ between the brain and the spinal cord results. Do you mind digging into that?

**Comment by zelenkastiot** [comment] 2021-08-02 01:37
Sure, I will look into it. Brief you tomorrow

**Comment by mathieuboudreau** [comment] 2021-09-03 14:44
Pinging @zelenkastiot – any ETA on looking into this?

**Comment by mathieuboudreau** [comment] 2022-06-16 18:44
Bug resolved in V2

**Closed by mathieuboudreau** 2022-06-16 18:44 UTC
