### ISSUE TITLE
Loosing link when annotating with Hypothesis

### ISSUE THREAD

**Issue by jcohenadad** [courtois-neuromod/anat-processing-book#5] opened 2021-07-05 20:11 UTC
When creating an annotation on the notebook using Hypothesis, if the annotation is addressed and another notebook is generated, it looks like the link send in response to the annotation is lost.

Ex: here is an email I received:
![image](https://user-images.githubusercontent.com/2482071/124514614-7068e200-ddab-11eb-9224-d3cef8299844.png)

When I click on [View the thread and respond](https://mandrillapp.com/track/click/30369633/hyp.is?p=eyJzIjoiYXNJTnF2V0FXX1VLM1RJQkJyWF9xVHFjM3BrIiwidiI6MSwicCI6IntcInVcIjozMDM2OTYzMyxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL2h5cC5pc1xcXC84ZWZmRU4yeEVldTd6Nk9zWG1wLTlBXFxcL2NvdXJ0b2lzLW5ldXJvbW9kLmdpdGh1Yi5pb1xcXC9hbmF0LXByb2Nlc3NpbmctYm9va1xcXC8wMVxcXC8xLXRlc3QuaHRtbFwiLFwiaWRcIjpcIjg1NTRlMDc3NDExYjQ5NWM4Zjg3ZGM3M2M5ZmM3ODgwXCIsXCJ1cmxfaWRzXCI6W1wiNzE3MWJiMDM1NWZkMGUzZWFiMDQ5MWMzNWJjY2UwZDY4NjdkMGM5N1wiXX0ifQ), I end up there:
![image](https://user-images.githubusercontent.com/2482071/124514643-87a7cf80-ddab-11eb-933f-e82e7d8c3645.png)

@zelenkastiot is that an expected behaviour? A bug? Do you suggest any alternative for commenting on the notebook?

**Comment by zelenkastiot** [comment] 2021-07-05 23:25
Hmm, it is not a bug since those cells where the comments were are now hidden/deleted. For the time being it is okay that we use it to comment since we always first comment then change it, at least before releasing the final version.  After the release of the book, I think it is a cool way to use this feature

**Comment by zelenkastiot** [comment] 2021-07-25 22:49
Hello @jcohenadad, should we close this issue since it's more of a bug on the Hypothesis side? 😃

**Closed** 2021-07-27 01:18 UTC
